### ISSUE TITLE
System Requirements in Readme Request

### ISSUE THREAD

**Issue by 08solsticegxp** [PREngineer/nZEDb-deploy#1]
I noticed there isn't anything for system requirements in the readme. Which Operating System is recommended. ect...

**Comment by porkie02** [comment]
ubuntu 14.04 I installed fine with, I run this in a unraid vm 2 cpus and 4gig ram, Its probably over kill but its seems ok for now. Just look at my issue reported to get it running sweetly and dont struggle like me for a couple of days.

**Comment by PREngineer** [comment]
I've been very busy lately but I will be adding the information in the Readme.  Thanks for pointing it out.

I usually use Ubuntu LTS (14.04 right now).

**Comment by porkie02** [comment]
I know what the issue is, the cronjobs do get added but to the wrong user, either root or nzedb I cant remember.

**Comment by PREngineer** [comment]
Recommended system specs have been added to Readme.

**Comment by 08solsticegxp** [comment]
That's great thanks

Dustin
