### ISSUE TITLE
Cron Jobs

### ISSUE THREAD

**Issue by porkie02** [PREngineer/nZEDb-deploy#2]
Great script and thanks for taking the time for doing this saves me so much headache. I did notice after a few days of trying to figure out was wrong. The cron jobs dont actually get added for whatever reason or not for me anytime Ive used the scripts I had to add them manually.

Also for anyone else trying to get irc working which took me a while cos of cron jobs and not understanding what to fill in on the ircscraper_settings.php part, just add a unique username in the first username part and that's it. Then add these cron jobs after install has finished.

`(crontab -l 2>/dev/null; echo "@reboot /bin/sleep 10; /usr/local/bin/znc >/dev/null 2>&1") | crontab -`

`(crontab -l 2>/dev/null; echo "@reboot /bin/sleep 10; /usr/bin/php /var/www/nzedb/misc/update/nix/tmux/start.php") | crontab -`

Now for everything works wells and tmux and irc scraper run on reboot with no issues.

**Comment by PREngineer** [comment]
Weird... don't know why it wasn't working when the exact same code is in my third script on lines #165 & #197.

Checked the code and it is just like you typed it.

I'm closing the issue.
