### ISSUE TITLE
"The temp unrar path is not a valid directory"

### ISSUE THREAD

**Issue by Hobbabobba** [PREngineer/nZEDb-deploy#3]
After Step 2 i get the error message "The temp unrar path is not a valid directory" when I use the Admin-Page.

**Comment by PREngineer** [comment]
It's likely that the path that you have for the location of UnRar is not where it actually is.

I would do:

"whereis unrar" to see where it is installed in your system and then use that path in the configuration.

**Comment by Hobbabobba** [comment]
it returns`/usr/bin/unrar` - copied it into the settings. Still the same error message.

**Comment by PREngineer** [comment]
Is there a path to temporarily unrar the files?

If there is, make sure to have read/write access to that.

Maybe that is what it refers to.

I've never gotten that error, so I don't know what is going on.

Make sure that all the folders that it is using are readable/writable.

**Comment by Hobbabobba** [comment]
solved. The problem:
`/var/www/nzedb/resources/tmp/` as the path for `Temp Unrar File Path` did not exist. 
So i changed it to `/var/www/nzedb/resources/` and everything is fine.

**Comment by PREngineer** [comment]
Awesome!  Thanks for letting people know.

**Comment by Hobbabobba** [comment]
this is the least i can do. thanks for your awesome script! saved me hours/days of work!
