### ISSUE TITLE
activate memcache properly

### ISSUE THREAD

**Issue by Hobbabobba** [PREngineer/nZEDb-deploy#5]
if you try the script `/var/www/nzedb/misc/testing/Tests/test_cache_server.php` you will notice, that nZEDb doesn´t use memcache.

To change it you need to change line `4081` in your script `nZEDb-2.sh` to
`sudo apt-get install memcached php5-memcached -y > /dev/null`
(one "d" was missing)  and you need to change the settings of nZEDb
```
cp /var/www/nzedb/nzedb/config/settings.example.php  /var/www/nzedb/nzedb/config/settings.php
sudo nano /var/www/nzedb/nzedb/config/settings.php
```
and change the cache type to
```
define('nZEDb_CACHE_TYPE', 1);
```

**Comment by soolhami** [comment]
Thanks for that

**Comment by PREngineer** [comment]
Hobbabobba,

Thanks for pointing out the error in the script.  I have fixed it.

This issue is closed.

A note on how to configure the settings will be put in the Readme too.

-------

Soolhami,

I'm glad it helped.  Sorry about leaving that typo there.
